version: '3'

services:
  app:
    build: .
    container_name: app-circulo-de-tinta
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:${PORT}
    volumes:
      - ./app:/app
    ports:
      - "${PORT}:8000"
    depends_on:
      - db_sql
      - db_nosql
  
  db_sql:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db_nosql:
    image: mongo:5.0
    container_name: mongo_db
    env_file:
      - .env
    volumes:
      - ./db/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"
